//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTac
    {
        public string MaCongTac { get; set; }
        public string MaNhanVien { get; set; }
        public string MaChucVu { get; set; }
        public string MaPhongBan { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<System.DateTime> NgayNhanChuc { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
