//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHSGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.Lops = new HashSet<Lop>();
            this.QuanLiGiangDays = new HashSet<QuanLiGiangDay>();
        }
    
        public string magiaovien { get; set; }
        public string hovaten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string tongiao { get; set; }
        public string quequan { get; set; }
        public string diachithuongtru { get; set; }
        public string sodienthoai { get; set; }
        public string hocvi { get; set; }
        public string chucvu { get; set; }
        public string chuyenmon { get; set; }
        public string tinhtrang { get; set; }
        public string luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLiGiangDay> QuanLiGiangDays { get; set; }
    }
}
